### ISSUE TITLE
First Issue

### ISSUE THREAD

**Issue by kojq** [Henryws/esoeditor#1]
What's this for? There's no `README.md`. Also, the implementation is a bit funny.

**Comment by Elsie19** [comment]
It's my esoteric editor I made because I'm bored. It's goal is to be as unfriendly as possible while still being technically usable.

-------- Mensaje original --------

**Comment by kojq** [comment]
If it is supposed to be esoteric, maybe introduce some solid paradigms. I suggest that because I think it can be unfriendly by forcing multiple complex actions for a single command, and that can get boring.

Is the plan to write this purely as shell script? Also, when do you think you'll stop working on it for good?

**Comment by Elsie19** [comment]
> maybe introduce some solid paradigms

Can you elaborate?

> forcing multiple complex actions for a single command

Same for this.

> Is the plan to write this purely as shell script?

Yup

> Also, when do you think you'll stop working on it for good?

When I'm bored of working on it. I don't have any hopes for it long term, just a random thing I'm working on.

**Comment by kojq** [comment]
> Can you elaborate?

Basic design guidelines

> Same for this.

For instance, press É followed by CTRL + é along with the line number formatted as the line number with the word "line" appended to the beginning to jump to the specified line.

**Comment by Elsie19** [comment]
I plan on everything being letter based (but idk, I don't really have any plans for formal design, nor do I really care), no ctrl stuff used.

**Comment by kojq** [comment]
Alright. You are planning to accept feature/bug requests and/or issues since this is public? Also, you can close with your next comment, if you want.

**Comment by Elsie19** [comment]
I guess, but it's not really something I envision getting a lot of attention. It's just a stupid editor I made because I was bored.
